services:

  #################################################### PUBLIC LAYER ####################################################

  # PubApi
  pub_api:
    container_name: pub_api
    build:
      context: ./pub_api
      dockerfile: PubApi.dev.dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./pub_api/src:/app/src
      - ./pub_api/Cargo.toml:/app/Cargo.toml
      - ./pub_api/Cargo.lock:/app/Cargo.lock
      - /app/target
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - indexer-net

  ############################################ PERSISTENCE AND CACHING LAYER ############################################

  #=================================================  POSTGRESQL / DB ==================================================

  # Postgres / DB
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: streamer_db_user
      POSTGRES_PASSWORD: streamer_db_password
      POSTGRES_DB: tokens_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U streamer_db_user -d tokens_db" ]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - '5432:5432'
    volumes:
      - .dbdata/postgres_data:/var/lib/postgresql/data
    networks:
      - indexer-net

  # PGAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - "8082:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - indexer-net
    volumes:
      - .dbdata/pgadmin_data:/var/lib/pgadmin

  #================================================= CLICKHOUSE / DB ==================================================

  # ClickHouse
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    environment:
      CLICKHOUSE_DB: events_db
      CLICKHOUSE_USER: clickhouse_user
      CLICKHOUSE_PASSWORD: clickhouse_password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - .dbdata/clickhouse_data:/var/lib/clickhouse
      - .dbdata/clickhouse_logs:/var/log/clickhouse-server
    healthcheck:
      test: [ "CMD", "clickhouse-client", "--query", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - indexer-net

  # CH UI
  clickhouse-ui:
    image: spoonest/clickhouse-tabix-web-client:latest
    container_name: clickhouse-ui
    ports:
      - "8083:80"
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - indexer-net

  #================================================= CACHE/ REDIS =====================================================

  # Redis
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - .dbdata/redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - indexer-net

  # Redis UI
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - indexer-net

  #=================================================== MINIO/ S3 =======================================================

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9100:9000"   # S3 API
      - "9101:9001"   # Web console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - .dbdata/minio-data:/data
    restart: unless-stopped

  ########################################## PROCESSING AND PRESERVATION LAYER ##########################################

  # DataProcessor
  data_processor:
    container_name: data_processor
    build:
      context: ./data_processor
      dockerfile: DataProcessor.dev.dockerfile
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./data_processor/src:/app/src
      - ./data_processor/Cargo.toml:/app/Cargo.toml
      - ./data_processor/Cargo.lock:/app/Cargo.lock
      - /app/target
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379/
      POSTGRES_DATABASE_URL: postgres://streamer_db_user:streamer_db_password@postgres:5432/tokens_db
      CLICKHOUSE_URL: http://clickhouse:8123
      CLICKHOUSE_USER: clickhouse_user
      CLICKHOUSE_PASSWORD: clickhouse_password
      CLICKHOUSE_DATABASE: events_db
      KAFKA_BROKERS: kafka:9092
      KAFKA_GROUP_ID: ch_consumer_group
      NEW_ACCOUNTS_CACHE_LIMIT: 10
      NEW_ACCOUNTS_KEY: new_accounts
    networks:
      - indexer-net

  ################################################### TRANSPORT LAYER ###################################################

  # Kafka
  kafka:
    container_name: kafka
    image: apache/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - .dbdata/kafka_data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    command:
      - /bin/sh
      - -c
      - |
        /etc/kafka/docker/run &
        sleep 15

        /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists --topic pf_trade_event --partitions 1 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists --topic pf_create_event --partitions 1 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists --topic pf_migrate_event --partitions 1 --replication-factor 1

        /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists --topic ps_trade_event --partitions 1 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists --topic pf_create_event --partitions 1 --replication-factor 1

        /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists --topic fulfill_req --partitions 1 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists --topic price_req --partitions 1 --replication-factor 1

        wait $KAFKA_PID
    networks:
      - indexer-net

  # KafkaUI
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - indexer-net

  ################################################## EXTRACTION LAYER ##################################################

  # GeyserAccountSubscriber
  geyser_account_subscriber:
    container_name: pumpfun_geyser_account_subscriber
    build:
      context: ./geyser_account_subscriber
      dockerfile: GeyserAccountSubscriber.dev.dockerfile
    restart: always
    ports:
      - "8004:8004"
    volumes:
      - ./geyser_account_subscriber/src:/app/src
      - ./geyser_account_subscriber/Cargo.toml:/app/Cargo.toml
      - ./geyser_account_subscriber/Cargo.lock:/app/Cargo.lock
      - /app/target
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - indexer-net

  # GeyserTxStreamer: streams transactions from protocols
  geyser_tx_streamer:
    container_name: geyser_tx_streamer
    build:
      context: ./geyser_tx_streamer
      dockerfile: GeyserTxStreamer.dev.dockerfile
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - ./geyser_tx_streamer/src:/app/src
      - ./geyser_tx_streamer/Cargo.toml:/app/Cargo.toml
      - ./geyser_tx_streamer/Cargo.lock:/app/Cargo.lock
      - /app/target
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - indexer-net

  # GapFiller: filling gaps on lacking data
  gap_filler:
    container_name: gap_filler
    build:
      context: ./gap_filler
      dockerfile: GapFiller.dev.dockerfile
    restart: always
    ports:
      - "8003:8003"
    volumes:
      - ./gap_filler/src:/app/src
      - ./gap_filler/Cargo.toml:/app/Cargo.toml
      - ./gap_filler/Cargo.lock:/app/Cargo.lock
      - /app/target
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - indexer-net

  # Historian: cron job to fulfill historical data
  historian:
    container_name: historian
    build:
      context: ./historian
      dockerfile: Historian.dev.dockerfile
    restart: always
    ports:
      - "8004:8004"
    volumes:
      - ./historian/src:/app/src
      - ./historian/Cargo.toml:/app/Cargo.toml
      - ./historian/Cargo.lock:/app/Cargo.lock
      - /app/target
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - indexer-net

  #################################################### OBSERVABILITY LAYER ####################################################

  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - indexer-net

  # Grafana
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - indexer-net

#################################################### NETWORK ####################################################

networks:
  indexer-net:
    driver: bridge
