apiVersion: v1
kind: Service
metadata:
  name: clickhouse-nodeport
  namespace: infrastructure
spec:
  type: NodePort
  selector:
    clickhouse.altinity.com/chi: clickhouse-cluster
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      nodePort: 31823
    - name: tcp
      port: 9000
      targetPort: 9000
      nodePort: 31900