apiVersion: v1
kind: Service
metadata:
  name: clickhouse-ui
  namespace: ui-tools
spec:
  type: NodePort
  selector:
    app: clickhouse-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083