apiVersion: v1
kind: Service
metadata:
  name: pump-api
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: pump-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800