apiVersion: v1
kind: ConfigMap
metadata:
  name: pump-data-pgsql-config
  namespace: microservices
data:
  DATABASE_URL: "postgres://streamer_db_user:streamer_db_password@postgres.infrastructure:5432/tokens_db"
  REDIS_URL: "redis://redis.infrastructure:6379"
  KAFKA_BROKERS: "kafka-cluster-kafka-bootstrap.kafka:9092"