apiVersion: v1
kind: ConfigMap
metadata:
  name: pump-geyser-account-subscriber-config
  namespace: microservices
data:
  REDIS_URL: "redis://redis.infrastructure:6379"
  KAFKA_BROKERS: "kafka-cluster-kafka-bootstrap.kafka:9092"