apiVersion: v1
kind: Service
metadata:
  name: pump-ws-streamer
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: pump-ws-streamer
  ports:
    - port: 8005
      targetPort: 8005
      nodePort: 30805